// Stvarni nazivi iz kataloga materijala (Lux-co, 08.10.2026) — korpus za testove prepoznavanja.
// [naziv, kategorija, jedinica]
export const LUXCO_CATALOG: [string, string, string][] = [
    ["Alu ram - sa staklom","Alu vrata","Kom"],
    ["103307087 Baglama 155 Crna","Okovi","Kom"],
    ["103356233 Prolaz za kabel pravok. s četk. protiv praš.","Okovi","Kom"],
    ["103370208 VOLPATO protuklizna podloga struktura valova crna","Okovi","m"],
    ["Aventos HF","Okovi","Kom"],
    ["Aventos HK-XS","Okovi","Kom"],
    ["Aventos HL Top","Okovi","Kom"],
    ["Baglama kriva (bez ublazivaca)","Okovi","Kom"],
    ["Baglama kriva (sa ublazivacem)","Okovi","Kom"],
    ["Baglama kriva (za Tip On)","Okovi","Kom"],
    ["Baglama kriva (za vrata sa metalnim ramom)","Okovi","Kom"],
    ["Baglama paralelna (bez ublazivaca)","Okovi","Kom"],
    ["Baglama paralelna (sa ublazivacem)","Okovi","Kom"],
    ["Baglama polukriva (bez ublazivaca)","Okovi","Kom"],
    ["Baglama polukriva (sa ublazivacem)","Okovi","Kom"],
    ["Baglama polukriva (za TIP ON)","Okovi","Kom"],
    ["Baglama ravna (bez ublazivaca)","Okovi","Kom"],
    ["Baglama ravna (sa ublazivacem)","Okovi","Kom"],
    ["Baglama ravna (za Tip On)","Okovi","Kom"],
    ["Baglame za vrata - Skrivene","Okovi","Kom"],
    ["Blanco select II","Okovi","Kom"],
    ["Blum Ambia line","Okovi","kom"],
    ["BLUM AVENTOS HK-XS/TIP-ON najjaci 103318364","Okovi","kom"],
    ["Blum Revego Duo - Packet doors","Okovi","kom"],
    ["Brava za vrata - AGB","Okovi","Kom"],
    ["Bravica","Okovi","Kom"],
    ["Celicne nivelirajuce nogice","Okovi","kom"],
    ["Cilindar (za vrata) 35 / 35","Okovi","Kom"],
    ["Coklo / Bijelo","Okovi","Kom"],
    ["Coklo / Crno mat","Okovi","Kom"],
    ["Crni vijci / za montiranje na zid","Okovi","Kom"],
    ["Drvena ručka","Okovi","Kom"],
    ["Gardarobni lift Bijeli kromirani 770-1200","Okovi","Kom"],
    ["GOLA Rujz Design, 2199C, BronzE","Okovi","kom"],
    ["GOLA Rujz Design, 2199L, BronzE","Okovi","kom"],
    ["Horizontalna Gola C","Okovi","Kom"],
    ["Horizontalna Gola L","Okovi","Kom"],
    ["Inoxni rukohvat za lift","Okovi","kom"],
    ["Izvlačna košara  VS TAL Gate 5 ŠK 600  103378397","Okovi","kom"],
    ["Izvlačna košara - VS TAL gate Planero 103378392","Okovi","Kom"],
    ["Izvlačna košara (za niski element) 150 PEKA 103369639","Okovi","kom"],
    ["Izvlačna košara za korpus (720x200)","Okovi","Kom"],
    ["Izvlačna košara za korpus (720x300)","Okovi","Kom"],
    ["Izvlačna košara za korpus (Visoka - ŠK=300)","Okovi","Kom"],
    ["Izvlačna košara za korpus (Visoka - ŠK=400)","Okovi","Kom"],
    ["Izvlačna vješalica 103381302","Okovi","Kom"],
    ["Izvlačna vješalica 300S 103381262","Okovi","Kom"],
    ["Kanta za smeće","Okovi","Kom"],
    ["Kriva Baglama za staklena vrata","Okovi","Kom"],
    ["Kutni Mehanizam - VS COR Flex Planero 103378388","Okovi","Kom"],
    ["Kutnik L Gola","Okovi","Kom"],
    ["Kutnik za LED - 103382973","Okovi","kom"],
    ["L nosači","Okovi","kom"],
    ["Lamelo Clamex P-14","Okovi","Kom"],
    ["LED profil Crni - 103331739 (bez ramena)","Okovi","kom"],
    ["LED profil U - 103331937","Okovi","Kom"],
    ["LED traka tačkasta - 103397002 5m","Okovi","kom"],
    ["LEGRABOX visina C 176.8 (bijeli) 500 103365777","Okovi","kom"],
    ["LEGRABOX visina C 176.8 (crni mat) 400 103360973","Okovi","Kom"],
    ["LEGRABOX visina M 90.3 (bijeli) 500 103365664","Okovi","kom"],
    ["LEGRABOX visina M 90.3 (crni mat) 400 103360925","Okovi","Kom"],
    ["Limovi za krevet","Okovi","Kom"],
    ["Magnet MACO M2 103330880","Okovi","Kom"],
    ["Metalna noga 150mm - Bijela","Okovi","Kom"],
    ["Metalna ručka - Za vrata","Okovi","Kom"],
    ["Metalna ukruta za krevet","Okovi","Kom"],
    ["Metalne nogice BIJELE 10cm","Okovi","Kom"],
    ["Metalne nogice CRNE 10cm","Okovi","Kom"],
    ["Metalne nogice SIVE 10cm","Okovi","Kom"],
    ["Nogice za kuhinje","Okovi","Kom"],
    ["Nogice za kuhinje 10cm","Okovi","Kom"],
    ["Nogice za kuhinje 18cm","Okovi","Kom"],
    ["Nosac police skriveni","Okovi","kom"],
    ["Nosac za ofinger Grude","Okovi","kom"],
    ["Nosači Gole","Okovi","Kom"],
    ["Nosači Gole 103338888","Okovi","kom"],
    ["Nosaci gornjih elemenata","Okovi","Kom"],
    ["Nosaci ofingera","Okovi","Kom"],
    ["Nosači ofingera Emir","Okovi","kom"],
    ["Nosači polica (skriveni) 16cm 103342456","Okovi","Kom"],
    ["Okov za kačenje reklame - Chanel","Okovi","Kom"],
    ["Okov za klizna vrata komode","Okovi","Kom"],
    ["Okov za panele","Okovi","Set"],
    ["Okretni točkići za namještaj","Okovi","Kom"],
    ["Ostale ručkice","Okovi","Kom"],
    ["Ovjes gornjih elemenata","Okovi","Kom"],
    ["Pločaste SOLIDO baglame","Okovi","Kom"],
    ["Pravolinijski točkovi","Okovi","Kom"],
    ["Profilna ručka Rujz Design, 658.35, SatBronzE","Okovi","kom"],
    ["Recepcija CV - Noge inox","Okovi","kom"],
    ["Rozetna za kablove","Okovi","Kom"],
    ["Rozetna za rupu","Okovi","Kom"],
    ["Rozetna za zrak","Okovi","Kom"],
    ["Ručka Grude","Okovi","Kom"],
    ["Ručke - 658.35 - 200 Bijela","Okovi","Kom"],
    ["Ručke - 658.35 - 200 Crna","Okovi","Kom"],
    ["Ručke - 658.35 - 50 Bijela","Okovi","Kom"],
    ["Ručke - 658.35 - 50 Crna","Okovi","Kom"],
    ["Ručke - 658.35 - 90 Bijela","Okovi","Kom"],
    ["Ručke - 658.35 - 90 Crna","Okovi","Kom"],
    ["Ručke - 709.16 - 1090 Crna","Okovi","Kom"],
    ["Ručke za kuhinju Emir A503","Okovi","kom"],
    ["Ručkica (okrugla ukopavajuća) U11.001 / 35","Okovi","Kom"],
    ["Ručkica (sisica)","Okovi","Kom"],
    ["Ručkica Alhena - 103305109","Okovi","Kom"],
    ["Ručkice 643.33","Okovi","Kom"],
    ["Ručkice 709.16 Antracit","Okovi","Kom"],
    ["Rukohvat","Okovi","Kom"],
    ["SERVETTO izvlacni štrik 103360832","Okovi","Kom"],
    ["Sige - Izvlačna kolona 200 103332815","Okovi","Kom"],
    ["Sige - Izvlačna kolona 300 103332816","Okovi","Kom"],
    ["Šipka (noga stola) Travnik","Okovi","kom"],
    ["Šipka za ofingere","Okovi","m"],
    ["Space tower Blum","Okovi","Kom"],
    ["STAR Klizna vrata","Okovi","Kom"],
    ["Šteke za vrata (cilindar)","Okovi","Kom"],
    ["Stelujuce nogice - 103323535","Okovi","Kom"],
    ["Tip - on (sa čahurom) Dugi","Okovi","Kom"],
    ["Tip on (sa čahurom)","Okovi","Kom"],
    ["Točkić 103355273 - 70Kg","Okovi","Kom"],
    ["Transformator L&S LED - 103383101","Okovi","kom"],
    ["Trio matica M10","Okovi","Kom"],
    ["Ukrute za sto Aamanns","Okovi","kom"],
    ["Umetak za pribor za jelo","Okovi","kom"],
    ["Univerzalna GOLA - Crna 103364670","Okovi","Kom"],
    ["Vertikalna Gola C","Okovi","Kom"],
    ["Vertikalna Gola L","Okovi","Kom"],
    ["Veznik za radne ploče 150mm","Okovi","Kom"],
    ["Vijci i metalne tiple","Okovi","Kom"],
    ["Vitris Supra - vodilice za klizna vrata","Okovi","Set"],
    ["Vodilice Blum ( potpuna izvlaka) 500","Okovi","Kom"],
    ["Vodilice Blum 250","Okovi","kom"],
    ["Vodilice Blum 270","Okovi","Kom"],
    ["Vodilice Blum 300","Okovi","Kom"],
    ["Vodilice Blum 350","Okovi","Kom"],
    ["Vodilice Blum 350 (Tip-on)","Okovi","Kom"],
    ["Vodilice Blum 400","Okovi","Kom"],
    ["Vodilice Blum 400 (Tip-on)","Okovi","Kom"],
    ["Vodilice Blum 450","Okovi","Kom"],
    ["Vodilice Blum 450 (Tip-on)","Okovi","Kom"],
    ["Vodilice Blum 500","Okovi","Kom"],
    ["Vodilice Blum 550","Okovi","Kom"],
    ["Vodilice Blum 550 (Tip-on)","Okovi","Kom"],
    ["Vodilice Blum 600","Okovi","Kom"],
    ["Vodilice Grass Dynapro 500mm","Okovi","Kom"],
    ["Vodilice Hafele 450","Okovi","Kom"],
    ["Vodilice Kuglične 250","Okovi","Kom"],
    ["Vodilice Kuglične 300","Okovi","Kom"],
    ["Vodilice Kuglične 350","Okovi","Kom"],
    ["Vodilice Kuglične 400","Okovi","Kom"],
    ["Vodilice Kuglične 450","Okovi","Kom"],
    ["Vodilice Kuglične 500","Okovi","Kom"],
    ["Vodilice Kuglične 550","Okovi","Kom"],
    ["Vodilice Kuglične 700","Okovi","Kom"],
    ["Vodilice za klizna vrata / Akril","Okovi","Kom"],
    ["Vodilice za klizna vrata / Furnir Hrast","Okovi","Kom"],
    ["Vodilice za klizna vrata / Iveral","Okovi","Kom"],
    ["VS COR Flex 1000 - 103378388 Kutni elemenat","Okovi","Kom"],
    ["VS COR Flex 1200 - 103331452 Kutni elemenat","Okovi","Kom"],
    ["VS ENVI Space sustav kanti za razvrst. otpada ŠK 800 mm","Okovi","kom"],
    ["Žaba baglama 170","Okovi","Kom"],
    ["Završeci za Gole C","Okovi","Kom"],
    ["Završeci za Gole L","Okovi","Kom"],
    ["Zir baglame","Okovi","Kom"],
    ["Bajcanje","Ostalo","m2"],
    ["Boja za MDF","Ostalo","m2"],
    ["Bronzani elementi","Ostalo","kom"],
    ["Čičak","Ostalo","m"],
    ["Električni sto","Ostalo","Kom"],
    ["Element od plexigalasa","Ostalo","Kom"],
    ["Kamen ploča","Ostalo","m²"],
    ["Kamena ploča","Ostalo","Kom"],
    ["Lakiranje","Ostalo","m2"],
    ["Led 2700K","Ostalo","Kom"],
    ["Metali za sto Granof","Ostalo","kom"],
    ["Nogice za krevet (mala soba) Emir","Ostalo","kom"],
    ["Nosači drvenog cokla","Ostalo","Kom"],
    ["Nosiva konstrukcija","Ostalo","kom"],
    ["Parsol / Gray","Ostalo","m2"],
    ["Planibel / Bronza","Ostalo","m2"],
    ["Plexiglas","Ostalo","m2"],
    ["Print za suprotnu stranu","Ostalo","Kom"],
    ["Print za vrata","Ostalo","Kom"],
    ["Staklo / Crveni lakobel","Ostalo","m2"],
    ["Staklo / Float Bež 1015","Ostalo","m2"],
    ["Staklo u boji","Ostalo","m2"],
    ["Struja","Ostalo","Kom"],
    ["Sudoper","Ostalo","Kom"],
    ["Sudoper Alveus Quadrix 60","Ostalo","kom"],
    ["Sudoper Blanco","Ostalo","kom"],
    ["Tapacirano sjedište","Ostalo","Kom"],
    ["Tapacirano uzglavlje Emir","Ostalo","kom"],
    ["U za ladice oko sifona","Ostalo","Kom"],
    ["Iveral / 2206 Fango","Ploča","kom"],
    ["Kronospan AL06 Brushed Bronze na MDFu","Ploča","kom"],
    ["KT / AL06 Brushed Bronze 23/0.8","Ploča","m"],
    ["KT / Siva U775 ST9 43 / 1","Ploča","m"],
    ["KT / W960 43/0.8","Ploča","kom"],
    ["LEGRABOX visina F 239.9 (bijeli) 500 103365891","Ploča","kom"],
    ["Sperploca savitljiva","Ploča","kom"],
    ["Akril / 3019 Sahara Cream","Ploče i trake","Kom"],
    ["Akril / Bijeli mat","Ploče i trake","Kom"],
    ["Akril / Crni mat","Ploče i trake","Kom"],
    ["Akril / Sivi mat","Ploče i trake","Kom"],
    ["Akril / Visoki sjaj 647","Ploče i trake","Kom"],
    ["Akril / Visoki sjaj Crni","Ploče i trake","Kom"],
    ["Antaro Tandembox Sivi - Dubina = 500mm","Ploče i trake","Kom"],
    ["Compact / - Crni IP / XS","Ploče i trake","Kom"],
    ["Compact / 4100x1300x12 - Bijeli","Ploče i trake","Kom"],
    ["Compact / Antracit","Ploče i trake","Kom"],
    ["Compact / Antracit 4100x1854","Ploče i trake","Kom"],
    ["Compact / Bijeli - bijelo jezgro","Ploče i trake","Kom"],
    ["Compact / Bijeli - crno jezgro","Ploče i trake","Kom"],
    ["Compact / Hrast","Ploče i trake","Kom"],
    ["Compact / Orah Arezzo","Ploče i trake","Kom"],
    ["Corian / Glacier White","Ploče i trake","Kom"],
    ["Extrudirana iverica (Šuplja)","Ploče i trake","Kom"],
    ["Furnir / Dimljeni Hrast","Ploče i trake","m2"],
    ["Furnir / Hrast","Ploče i trake","m2"],
    ["Furnir / Jasen","Ploče i trake","m2"],
    ["Furnir / Jela Smrča","Ploče i trake","m2"],
    ["Furnir / Orah","Ploče i trake","m2"],
    ["Furnir / Tik","Ploče i trake","m²"],
    ["Furnir KK / Hrast","Ploče i trake","m2"],
    ["Furnir KK / Jasen","Ploče i trake","m²"],
    ["Furnir KK / Jela Smrča","Ploče i trake","m2"],
    ["Furnir KK / Orah","Ploče i trake","m2"],
    ["Gladstone Gray H3316 ST28","Ploče i trake","Kom"],
    ["GTV vodilica stara","Ploče i trake","kom"],
    ["HPL / 0125 Fundermax","Ploče i trake","Kom"],
    ["HPL / 0606 Arctic Bijela","Ploče i trake","Kom"],
    ["HPL / 2206 Fango","Ploče i trake","Kom"],
    ["HPL / 2296 Snow White Fundermax","Ploče i trake","Kom"],
    ["HPL / 3393 Batist","Ploče i trake","Kom"],
    ["HPL / Bakar","Ploče i trake","Kom"],
    ["HPL / Bijeli mat","Ploče i trake","Kom"],
    ["HPL / F205 Pietra","Ploče i trake","Kom"],
    ["HPL / F243","Ploče i trake","Kom"],
    ["HPL / F416 Textil","Ploče i trake","Kom"],
    ["HPL / F800","Ploče i trake","Kom"],
    ["HPL / H1180 ST37 Halifax","Ploče i trake","Kom"],
    ["HPL / H3710 Orah","Ploče i trake","Kom"],
    ["HPL / H3730","Ploče i trake","Kom"],
    ["HPL / Orah Arezzo","Ploče i trake","Kom"],
    ["HPL / Sivi - 0077","Ploče i trake","Kom"],
    ["HPL / U216 ST9","Ploče i trake","Kom"],
    ["HPL / U702","Ploče i trake","Kom"],
    ["HPL / U963 Siva","Ploče i trake","Kom"],
    ["HPL KK / Bijela","Ploče i trake","Kom"],
    ["Iveral / Bardolino H1145","Ploče i trake","Kom"],
    ["Iveral / Bež U222 ST9","Ploče i trake","Kom"],
    ["Iveral / Bijela Keramika F812","Ploče i trake","Kom"],
    ["Iveral / Bijeli 16","Ploče i trake","Kom"],
    ["Iveral / Bijeli za korpus","Ploče i trake","Kom"],
    ["Iveral / Bijeli za korpus 14mm","Ploče i trake","Kom"],
    ["Iveral / Crni 10mm","Ploče i trake","Kom"],
    ["Iveral / Crni U999 ST9","Ploče i trake","Kom"],
    ["Iveral / Diamond Gray U963 ST9 16mm","Ploče i trake","Kom"],
    ["Iveral / Diamond Gray U963 ST9 18mm","Ploče i trake","Kom"],
    ["Iveral / F206 Pietra Grigia Crna","Ploče i trake","Kom"],
    ["Iveral / F416 Textil Bež","Ploče i trake","Kom"],
    ["Iveral / F433 Textil tamni","Ploče i trake","Kom"],
    ["Iveral / Grafitno crna U961 ST7","Ploče i trake","Kom"],
    ["Iveral / H1113 ST10","Ploče i trake","Kom"],
    ["Iveral / H1180 ST37 Halifax","Ploče i trake","Kom"],
    ["Iveral / H3170 Kendal Hrast Natur","Ploče i trake","kom"],
    ["Iveral / H3359 ST32 18 - 6","Ploče i trake","Kom"],
    ["Iveral / H3395 Hrast","Ploče i trake","Kom"],
    ["Iveral / Hamilton H3303 ST10","Ploče i trake","Kom"],
    ["Iveral / Hrast - H3730","Ploče i trake","Kom"],
    ["Iveral / Kesten H1710 ST10","Ploče i trake","Kom"],
    ["Iveral / Orah - Arezzo 0260","Ploče i trake","Kom"],
    ["Iveral / Orah H3710 ST12","Ploče i trake","Kom"],
    ["Iveral / Pistacija U608 ST9","Ploče i trake","Kom"],
    ["Iveral / Porculan bijela W1200","Ploče i trake","Kom"],
    ["Iveral / Sivi - 0741","Ploče i trake","Kom"],
    ["Iveral / Sivi - U201 ST9","Ploče i trake","Kom"],
    ["Iveral / Sivi - U707","Ploče i trake","Kom"],
    ["Iveral / Sivi - U727 ST9","Ploče i trake","Kom"],
    ["Iveral / Sivi - U732 ST9","Ploče i trake","Kom"],
    ["Iveral / U104 Alabaster bijela","Ploče i trake","Kom"],
    ["Iveral / U115 ST9","Ploče i trake","Kom"],
    ["Iveral / U156 ST9","Ploče i trake","Kom"],
    ["Iveral / U216 ST9","Ploče i trake","Kom"],
    ["Iveral / U603","Ploče i trake","Kom"],
    ["Iveral / U665 Zelena","Ploče i trake","kom"],
    ["Iveral / U702 ST9","Ploče i trake","Kom"],
    ["Iveral / U775 ST9 Siva","Ploče i trake","Kom"],
    ["Iveral / U899 ST9","Ploče i trake","Kom"],
    ["Iveral / Vicenza H3157 ST12","Ploče i trake","Kom"],
    ["Iveral / W1000 Bijela","Ploče i trake","Kom"],
    ["Iveral / W960 Klasik bijela","Ploče i trake","Kom"],
    ["Iveral Bijeli - Vlagoodbojni","Ploče i trake","Kom"],
    ["Iverica sirova - Vlagoodbojna","Ploče i trake","Kom"],
    ["J / s masiv","Ploče i trake","m3"],
    ["Keramičke pločice","Ploče i trake","m2"],
    ["Kerrock / Arctic white 100","Ploče i trake","Kom"],
    ["Kerrock / Bijeli","Ploče i trake","Kom"],
    ["Kerrock Bijeli 3600x1310x12","Ploče i trake","kom"],
    ["KT / 0125 Fundermax","Ploče i trake","m"],
    ["KT / 2206 Fango","Ploče i trake","m"],
    ["KT / 2296 Snow White Fundermax 1.5mm 22 / 1","Ploče i trake","m"],
    ["KT / 3019 Sahara Cream 22 / 1","Ploče i trake","m"],
    ["KT / 3393 Batist","Ploče i trake","m"],
    ["KT / AF35 siva 23/0.8","Ploče i trake","m"],
    ["KT / Bardolino H1145","Ploče i trake","m"],
    ["KT / Bež U222 ST9","Ploče i trake","m"],
    ["KT / Bež U222 ST9 42 / 1","Ploče i trake","m"],
    ["KT / Bijela Keramika F812","Ploče i trake","m"],
    ["KT / Bijela mat 22 / 1","Ploče i trake","m"],
    ["KT / Bijela za korpus 22 / 1","Ploče i trake","m"],
    ["KT / Bijela za korpus 42 / 1","Ploče i trake","m"],
    ["KT / Crna mat 22 / 1","Ploče i trake","m"],
    ["KT / Crna U999 ST9 23/0.8","Ploče i trake","m"],
    ["KT / Diamond Gray U963 ST9 22 / 0.8","Ploče i trake","m"],
    ["KT / Diamond Gray U963 ST9 42 / 0.8","Ploče i trake","m"],
    ["KT / F205 Pietra","Ploče i trake","m"],
    ["KT / F206 23 / 0.8","Ploče i trake","m"],
    ["KT / F206 43 / 0.8","Ploče i trake","m"],
    ["KT / F243 22 / 1","Ploče i trake","m"],
    ["KT / F243 42 / 1","Ploče i trake","m"],
    ["KT / F433 Textil tamni 22 / 1","Ploče i trake","m"],
    ["KT / F800 22 / 1","Ploče i trake","m"],
    ["KT / Furnir Hrast 24 / 1","Ploče i trake","m"],
    ["KT / Furnir hrast 42 / 1","Ploče i trake","m"],
    ["KT / Gladstone Gray H3316 ST28 22 / 1","Ploče i trake","m"],
    ["KT / Grafitno crna U961 ST7","Ploče i trake","m"],
    ["KT / H1180 ST37 Halifax 22 / 1","Ploče i trake","m"],
    ["KT / H1180 ST37 Halifax 42 / 1","Ploče i trake","m"],
    ["KT / H3170 Kendal Hrast Natur 22/1","Ploče i trake","m"],
    ["KT / H3395 23 / 0.8","Ploče i trake","m"],
    ["KT / H3395 43 / 0.8","Ploče i trake","m"],
    ["KT / Hamilton H3303 ST10 22 / 1","Ploče i trake","m"],
    ["KT / Hamilton H3303 ST10 42 / 1","Ploče i trake","m"],
    ["KT / Hrast H1113 ST10 42 / 2","Ploče i trake","m"],
    ["KT / Hrast H3730 23/0.8","Ploče i trake","m"],
    ["KT / Kesten H1710 42 / 1","Ploče i trake","m"],
    ["KT / Orah 22 / 1","Ploče i trake","m"],
    ["KT / Orah 43 / 1","Ploče i trake","m"],
    ["KT / Orah Arrezo","Ploče i trake","m"],
    ["KT / Orah H3710 ST12","Ploče i trake","m"],
    ["KT / Orah H3710 ST12 43 / 1","Ploče i trake","m"],
    ["KT / Pistacija U608 ST9 23/0.8","Ploče i trake","m"],
    ["KT / Porculan bijela W1200 23 / 1","Ploče i trake","m"],
    ["KT / Porculan bijela W1200 43 / 1","Ploče i trake","m"],
    ["KT / Siva 0077 22 / 1","Ploče i trake","m"],
    ["KT / Siva mat","Ploče i trake","m"],
    ["KT / Siva U201 ST9 22 / 1","Ploče i trake","m"],
    ["KT / Siva U702 ST9 23 / 0.8","Ploče i trake","m"],
    ["KT / Siva U702 ST9 42 / 1","Ploče i trake","m"],
    ["KT / Siva U707 ST9 22 / 1","Ploče i trake","m"],
    ["KT / Siva U707 ST9 42 / 1","Ploče i trake","Kom"],
    ["KT / Siva U727 ST9 23/0.8","Ploče i trake","m"],
    ["KT / Siva U732 ST9 22 / 1","Ploče i trake","m"],
    ["KT / Siva U732 ST9 42 / 1","Ploče i trake","m"],
    ["KT / Siva U775 ST9 22 / 1","Ploče i trake","m"],
    ["KT / Textil F416 22 / 1","Ploče i trake","m"],
    ["KT / Textil F416 42 / 1","Ploče i trake","m"],
    ["KT / U104 23 / 0.8","Ploče i trake","m"],
    ["KT / U115 ST9","Ploče i trake","m"],
    ["KT / U156 23/0.8","Ploče i trake","m"],
    ["KT / U216 ST9","Ploče i trake","m"],
    ["KT / U603 22 / 1","Ploče i trake","m"],
    ["KT / U665 Zelena","Ploče i trake","m"],
    ["KT / U899 ST9 22 / 1","Ploče i trake","m"],
    ["KT / Vicenza H3157 ST12 23 / 0.8","Ploče i trake","m"],
    ["KT / Vicenza H3157 ST12 42 / 0.8","Ploče i trake","m"],
    ["KT / Visoki sjaj 647","Ploče i trake","m"],
    ["KT / W1000 Premium bijela","Ploče i trake","Kom"],
    ["KT / W960 23 / 0.8","Ploče i trake","m"],
    ["Lamistal","Ploče i trake","m2"],
    ["Lesomal","Ploče i trake","Kom"],
    ["Masiv / Homara","Ploče i trake","m3"],
    ["Masiv / Hrast","Ploče i trake","m3"],
    ["Masiv / Jasen","Ploče i trake","m3"],
    ["Masiv / Lipa","Ploče i trake","m3"],
    ["Masiv / Orah","Ploče i trake","m3"],
    ["Masiv / Sibirski ariš","Ploče i trake","kom"],
    ["Masiv Tik","Ploče i trake","m²"],
    ["MDF 10","Ploče i trake","Kom"],
    ["MDF 12","Ploče i trake","Kom"],
    ["MDF 12 Negorivi","Ploče i trake","Kom"],
    ["MDF 14","Ploče i trake","Kom"],
    ["MDF 16","Ploče i trake","Kom"],
    ["MDF 18","Ploče i trake","Kom"],
    ["MDF 18 Negorivi","Ploče i trake","Kom"],
    ["MDF 22","Ploče i trake","Kom"],
    ["MDF 28","Ploče i trake","Kom"],
    ["MDF 3","Ploče i trake","Kom"],
    ["MDF 6","Ploče i trake","Kom"],
    ["MDF 8","Ploče i trake","Kom"],
    ["MDF Vlagoodbojni","Ploče i trake","Kom"],
    ["Multipleks Šperploča","Ploče i trake","kom"],
    ["Oblikovna špera","Ploče i trake","Kom"],
    ["OSB 12","Ploče i trake","Kom"],
    ["OSB 15","Ploče i trake","Kom"],
    ["OSB 18","Ploče i trake","Kom"],
    ["Panel ploča / Masivna Smreka","Ploče i trake","Kom"],
    ["Radna ploča /","Ploče i trake","Kom"],
    ["Radna ploča / Crna - U999","Ploče i trake","Kom"],
    ["Radna ploča / H3710 Orah","Ploče i trake","Kom"],
    ["Radna ploča / Vicenza H3157 ST12","Ploče i trake","Kom"],
    ["Rigips ploče","Ploče i trake","m2"],
    ["Ručke - u6.137 Crna","Ploče i trake","kom"],
    ["Sirova iverica","Ploče i trake","Kom"],
    ["Šperploča breza CP / C 12","Ploče i trake","Kom"],
    ["Šperploča breza CP/C, WBP","Ploče i trake","kom"],
    ["Šperploča EU breza S/BB","Ploče i trake","kom"],
    ["Sperploca Topola BB / BB18","Ploče i trake","Kom"],
    ["Staklena vuna","Ploče i trake","m2"],
    ["Staro drvo - Panel","Ploče i trake","m²"],
    ["Ogledalo / Clear","Staklo","m2"],
    ["Ogledalo Bronza","Staklo","m2"],
    ["Parsol / Bronza","Staklo","m²"],
    ["Staklo / Bež lakobel","Staklo","m2"],
    ["Staklo / Crno emajlirano","Staklo","m2"],
    ["Staklo / Crno lakobel","Staklo","m2"],
    ["Staklo / Float","Staklo","m2"],
    ["Staklo / Float Crna 9005","Staklo","m2"],
    ["Staklo / Flutes","Staklo","m2"],
    ["Staklo / Tonirano","Staklo","m2"],
    ["Termo staklo","Staklo","m2"],
];
